const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Buyurtmalar',
      quantity: 15,
    img: './Assets/Images/Home.png',},
    {
      id: 2,
      title: 'diner double',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Customers',
      quantity: 13,
    img: './Assets/Images/Home.png',},
    {
      id: 3,
      title: 'godzilla milkshake',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Toifalar',
      quantity: 6,
    img: './Assets/Images/Home.png',},
    {
      id: 4,
      title: 'country delight',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Mahsulotlar',
      quantity: 20,
    img: './Assets/Images/Home.png',},
    {
      id: 5,
      title: 'egg attack',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Texnologiyalar',
      quantity: 22,
    img: './Assets/Images/Home.png',},
    {
      id: 6,
      title: 'oreo dream',
      number:"+998931487733",
      name:"Eko Matras",
      category: 'Manzil',
      quantity: 18,
   img: './Assets/Images/Home.png'},
   {
    id: 7,
    title: 'diner double',
    number:"+998931487733",
    name:"Eko Matras",
    category: 'Customers',
    quantity: 13,
  img: './Assets/Images/Home.png'},
  {
    id: 8,
    title: 'neruble',
    number:"+99893148783",
    name:"Eko Matras",
    category: 'Customers',
    quantity: 13,
  img: './Assets/Images/Home.png'},

  ];
  export default menu;